Annotate Source Code in PRs
getappmap/analyze-action pull request #20
Opened 2023-07-20 17:23 UTC by ahtrotta

2023-07-25 17:23 UTC, kgilpin commented on src/Annotator.ts
> +    let preferredLocation = locationInfo.find((info) => info && !path.isAbsolute(info.path));
In CI, we often see Ruby gems bundled into the _vendor_ directory, and it's also possible to see _node_modules_, so we should probably exclude any code that's in these directories, even if it's a relative path.

We should also add a property to the Action that allows the user to specify additionl directories to consider "non-local".

2023-07-25 17:34 UTC, kgilpin requested changes
I am seeing this fetch error in the Analyze action: ```/home/runner/work/analyze-action/analyze-action/dist/webpack:/preflight-appmap-action/node_modules/@octokit/core/node_modules/@octokit/request/dist-node/index.js:57
    throw new Error(
^
Error: fetch is not set. Please pass a fetch implementation as new Octokit({ request: { fetch }}). Learn more at https://github.com/octokit/octokit.js/#fetch-missing
    at fetchWrapper (/home/runner/work/analyze-action/analyze-action/dist/webpack:/preflight-appmap-action/node_modules/@octokit/core/node_modules/@octokit/request/dist-node/index.js:57:1)
    at request2 (/home/runner/work/analyze-action/analyze-action/dist/webpack:/preflight-appmap-action/node_modules/@octokit/core/node_modules/@octokit/request/dist-node/index.js:172:1)
    at hook (/home/runner/work/analyze-action/analyze-action/dist/webpack:/preflight-appmap-action/node_modules/@octokit/auth-token/dist-node/index.js:58:1)
    at /home/runner/work/analyze-action/analyze-action/dist/webpack:/preflight-appmap-action/node_modules/@octokit/plugin-request-log/dist-node/index.js:37:1
    at /home/runner/work/analyze-action/analyze-action/dist/webpack:/preflight-appmap-action/node_modules/before-after-hook/lib/register.js:25:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.next (/home/runner/work/analyze-action/analyze-action/dist/webpack:/preflight-appmap-action/node_modules/@octokit/plugin-paginate-rest/dist-node/index.js:76:1)```

2023-07-26 20:01 UTC, ahtrotta commented
> I am seeing this fetch error in [the Analyze step](https://github.com/getappmap/analyze-action/actions/runs/5659846544/job/15334267218):
> 
> ```
> 
> /home/runner/work/analyze-action/analyze-action/dist/webpack:/preflight-appmap-action/node_modules/@octokit/core/node_modules/@octokit/request/dist-node/index.js:57
>     throw new Error(
> ^
> Error: fetch is not set. Please pass a fetch implementation as new Octokit({ request: { fetch }}). Learn more at https://github.com/octokit/octokit.js/#fetch-missing
>     at fetchWrapper (/home/runner/work/analyze-action/analyze-action/dist/webpack:/preflight-appmap-action/node_modules/@octokit/core/node_modules/@octokit/request/dist-node/index.js:57:1)
>     at request2 (/home/runner/work/analyze-action/analyze-action/dist/webpack:/preflight-appmap-action/node_modules/@octokit/core/node_modules/@octokit/request/dist-node/index.js:172:1)
>     at hook (/home/runner/work/analyze-action/analyze-action/dist/webpack:/preflight-appmap-action/node_modules/@octokit/auth-token/dist-node/index.js:58:1)
>     at /home/runner/work/analyze-action/analyze-action/dist/webpack:/preflight-appmap-action/node_modules/@octokit/plugin-request-log/dist-node/index.js:37:1
>     at /home/runner/work/analyze-action/analyze-action/dist/webpack:/preflight-appmap-action/node_modules/before-after-hook/lib/register.js:25:1
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at Object.next (/home/runner/work/analyze-action/analyze-action/dist/webpack:/preflight-appmap-action/node_modules/@octokit/plugin-paginate-rest/dist-node/index.js:76:1)```
> ```

This error disappears when using `getOctokit` instead of `new Octokit`, so I changed the code [here](https://github.com/getappmap/analyze-action/pull/20/commits/74b9b02c6a4e30865281c74be7e6429317776448#diff-491511c04c698dc5c1b49979afef8c4065b7fc9c4caf8d7c14f80537535c6442R81).

2023-07-26 20:05 UTC, kgilpin commented
> > I am seeing this fetch error in [the Analyze step](https://github.com/getappmap/analyze-action/actions/runs/5659846544/job/15334267218):
> > ```
> > 
> > /home/runner/work/analyze-action/analyze-action/dist/webpack:/preflight-appmap-action/node_modules/@octokit/core/node_modules/@octokit/request/dist-node/index.js:57
> >     throw new Error(
> > ^
> > Error: fetch is not set. Please pass a fetch implementation as new Octokit({ request: { fetch }}). Learn more at https://github.com/octokit/octokit.js/#fetch-missing
> >     at fetchWrapper (/home/runner/work/analyze-action/analyze-action/dist/webpack:/preflight-appmap-action/node_modules/@octokit/core/node_modules/@octokit/request/dist-node/index.js:57:1)
> >     at request2 (/home/runner/work/analyze-action/analyze-action/dist/webpack:/preflight-appmap-action/node_modules/@octokit/core/node_modules/@octokit/request/dist-node/index.js:172:1)
> >     at hook (/home/runner/work/analyze-action/analyze-action/dist/webpack:/preflight-appmap-action/node_modules/@octokit/auth-token/dist-node/index.js:58:1)
> >     at /home/runner/work/analyze-action/analyze-action/dist/webpack:/preflight-appmap-action/node_modules/@octokit/plugin-request-log/dist-node/index.js:37:1
> >     at /home/runner/work/analyze-action/analyze-action/dist/webpack:/preflight-appmap-action/node_modules/before-after-hook/lib/register.js:25:1
> >     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> >     at Object.next (/home/runner/work/analyze-action/analyze-action/dist/webpack:/preflight-appmap-action/node_modules/@octokit/plugin-paginate-rest/dist-node/index.js:76:1)```
> > ```
> 
> This error disappears when using `getOctokit` instead of `new Octokit`, so I changed the code [here](https://github.com/getappmap/analyze-action/pull/20/commits/74b9b02c6a4e30865281c74be7e6429317776448#diff-491511c04c698dc5c1b49979afef8c4065b7fc9c4caf8d7c14f80537535c6442R81).

Weird. Good job finding the fix.

2023-07-27 18:25 UTC, kgilpin approved these changes

2023-07-27 18:25 UTC, merged